{{- $saName := .Values.serviceAccount.name | default "token-manager-sa" -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: token-manager
    release: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-token-manager-role
  labels:
    app: token-manager
    release: {{ .Release.Name }}
rules:
  - apiGroups: ["hypershift.openshift.io"]
    resources: ["hostedclusters"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-token-manager-binding
  labels:
    app: token-manager
    release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ $saName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-token-manager-role
  apiGroup: rbac.authorization.k8s.io