image:
  repository: ghcr.io/dana-team/token-manager
  tag: ""

config:
  clusterDomain: "apps-example-com"
  schedule: "0 0 * * *"

remotes:
  - name: us-east-1
    url: ""
    token: ""
  - name: us-east-2
    url: ""
    token: ""

serviceAccount:
  name: "token-manager-sa"

